import Head from "next/head";
import Image from "next/image";
import Commodities from "../components/Commodities";
import LineChart from "../components/LineChart";
import styles from "../styles/Home.module.css";

// export async function getServerSideProps() {
//   const [ibmRes, gtRes, dailyRes, timeSeriesRes] = await Promise.all([
//     fetch(
//       `https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey=${process.env.REACT_APP_ALPHA_VANTAGE}`
//     ),
//     fetch(
//       `https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=GT&apikey=${process.env.REACT_APP_ALPHA_VANTAGE}`
//     )
// fetch(
//   `https://commodities-api.com/api/latest?access_key=${process.env.REACT_APP_COMMODITIES_API}`
// ),
// fetch(
//   `https://commodities-api.com/api/timeseries?access_key=${process.env.REACT_APP_COMMODITIES_API}&start_date=2022-01-01&end_date=2022-01-05&symbols=ALU`
// ),
// ]);
// const [ibm, gt, daily, timeSeries] = await Promise.all([
//   ibmRes.json(),
//   gtRes.json(),
// dailyRes.json(),
// timeSeriesRes.json(),
// ]);

//   return {
//     props: { ibm, gt, daily },
//   };
// }

export default function Home({ gt, daily }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {/* <div className="text-">{daily.data.date}</div> */}
        {/* <div>{ibm}</div> */}
        {/* <LineChart data={data} interval={"Time Series (5min)"} /> */}
        {/* <LineChart data={gt} interval={"Time Series (Daily)"} /> */}
        <Commodities />
      </main>
    </div>
  );
}
